[package]
name = "physics"
version = "0.2.0"
edition = "2021"

[dependencies]
ecs = { path = "../ecs" }
log = { workspace = true }
rapier2d = { workspace = true, optional = true }

[features]
default = ["rapier"]
rapier = ["dep:rapier2d"]
simple = []
