[package]
name = "script"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.9", features = ["lua54", "vendored"] }
anyhow = "1.0"
ecs = { path = "../ecs" }
input = { path = "../input" }
log = "0.4"
